# Generated by Django 4.2.16 on 2025-08-02 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('reference', models.ImageField(blank=True, null=True, upload_to='reference')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pdesc', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('fancy candle', 'Fancy Candle'), ('birthday candle', 'Birthday Candle'), ('home decor', 'Home Decor'), ('accessories', 'Accessories'), ('spa candle', 'Spa Candle'), ('study candle', 'Study Candle'), ('romentic candle', 'Romantic Candle'), ('gift', 'Gift'), ('festival canlde', 'Festival Candle'), ('other', 'Other'), ('candle holder', 'Candle Holder'), ('scented candle', 'Scented Candle'), ('unscented candle', 'Unscented Candle'), ('pillar candle', 'Pillar Candle'), ('tealight candle', 'Tealight Candle'), ('votive candle', 'Votive Candle'), ('jar candle', 'Jar Candle'), ('soy candle', 'Soy Candle'), ('beeswax candle', 'Beeswax Candle'), ('paraffin candle', 'Paraffin Candle'), ('candle making kit', 'Candle Making Kit'), ('candle accessories', 'Candle Accessories'), ('candle gift set', 'Candle Gift Set')], max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prod')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_images', to='home.prod')),
            ],
        ),
    ]
